apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      imagePullSecrets:
        - name: nexus-regcred
      containers:
        - name: petclinic
          image: 13.232.220.193:8082/docker-hosted/petclinic:1
          ports:
            - containerPort: 8080
